# swagger 配置
swagger:
  enabled: true
  title: PigX Swagger API
  gateway: http://${GATEWAY-HOST:topway-gateway}:${GATEWAY-PORT:9999}
  token-url: ${swagger.gateway}/auth/oauth2/token
  scope: server
