# 数据源
spring:
  redis:
    host: topway-redis
    database: 9  #避免和微服务 PIGX 冲突
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://topway-mysql:3306/topway_boot_codegen?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
  web:
    resources:
      static-locations: classpath:/static/,classpath:/views/

# 租户表维护
topway:
  tenant:
    column: tenant_id
    tables:
      - gen_datasource_conf
      - gen_form_conf
      - gen_template
      - gen_group
